language: node_js
node_js:
  - "node"
cache: false
before_install:
  - yarn global add exp@50.0.0
script:
  - 'export BRANCH="$TRAVIS_PULL_REQUEST_SLUG#$TRAVIS_PULL_REQUEST_BRANCH"'
  - 'echo $BRANCH'
  - 'if [ "$TRAVIS_PULL_REQUEST_SLUG" != "FaridSafi/react-native-gifted-chat" ]; then echo "No appr because external PR"; else yarn appr; fi'
