language: node_js
node_js:
  - "node"
cache: yarn
script:
  - 'export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "$TRAVIS_REPO_SLUG#$TRAVIS_BRANCH"; else echo "$TRAVIS_PULL_REQUEST_SLUG#$TRAVIS_PULL_REQUEST_BRANCH"; fi)'
  - 'echo "BRANCH=$BRANCH"'
  - 'yarn appr'
