name: Main CI

on:
  pull_request:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Node modules
        run: |
          yarn install

      - name: Lint
        run: |
          yarn build
